In [1]:
from cocoAI.FEC import main
from common.path import DATA_PATH

excel_path_list = list(DATA_PATH.glob("202*xls*"))[:2]
main(excel_path_list)

logfile available C:\Users\lvolat\Documents\cocoAI\cocoAI\ipykernel_launcher.log
 Bilan :
           Catégorie      Montant
0            Actifs  14442332.82
1           Passifs  23036481.06
2  Capitaux Propres   3825419.52
3       Total Bilan  -8594148.24

 Compte de Résultat :
       Catégorie     Montant
0      Produits  8912805.87
1       Charges  7720730.50
2  Résultat Net  1192075.37

 Tableau de Flux de Trésorerie :
                  Catégorie     Montant
0       Flux Opérationnels  -467621.59
1     Flux Investissements  2371867.93
2        Flux Financements  1114741.65
3  Variation de Trésorerie  3018987.99

 Présentation Beamer générée : presentation_beamer.tex

In [2]:
from cocoAI.FEC import load_excel_data, load_nomenclature


excel_path_list = list(DATA_PATH.glob("202*xls*"))[:2]
df = load_excel_data(excel_path_list)
df = df.reset_index()
dfnom = load_nomenclature()
dfnom = dfnom.reset_index()

# main(excel_path_list)

cocoAI - INFO - C:\Users\lvolat\Documents\cocoAI\common\nomenclature.yaml loaded

In [3]:
df['Classe'] = df['Compte'].apply(lambda x:str(x)[:1])
df['niveau1'] = df['Compte'].apply(lambda x:str(x)[:2])
df['niveau2'] = df['Compte'].apply(lambda x:str(x)[:3])
df['niveau3'] = df['Compte'].apply(lambda x:str(x)[:4])
df['niveau4'] = df['Compte'].apply(lambda x:str(x)[:5])
dft = df.merge(dfnom,on='niveau1')

In [4]:
dft

,index_x,Compte,Intitulé,Date,Journal,Libellé,Rèf pièce,Débit,Let.,Crédit,Solde,Classe_x,niveau1,niveau2_x,niveau3,niveau4,index_y,Classe_y,description,niveau2_y
0,4,101300,Cap.souscr. appele verse,01/01/2022,AN,REPRISE A NOUVEAU,NaN,0.0,NaN,153000.00,-153000.00,1,10,101,1013,10130,1,1,Capital et réserves,NaN
1,4,101300,Cap.souscr. appele verse,01/01/2022,AN,REPRISE A NOUVEAU,NaN,0.0,NaN,153000.00,-153000.00,1,10,101,1013,10130,2,1,Capital,101
2,4,101300,Cap.souscr. appele verse,01/01/2022,AN,REPRISE A NOUVEAU,NaN,0.0,NaN,153000.00,-153000.00,1,10,101,1013,10130,3,1,Fonds fiduciaires,102
3,4,101300,Cap.souscr. appele verse,01/01/2022,AN,REPRISE A NOUVEAU,NaN,0.0,NaN,153000.00,-153000.00,1,10,101,1013,10130,4,1,Primes liées au capital social,104
4,4,101300,Cap.souscr. appele verse,01/01/2022,AN,REPRISE A NOUVEAU,NaN,0.0,NaN,153000.00,-153000.00,1,10,101,1013,10130,5,1,Écarts de réévaluation,105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586216,34815,791000,Indemnités et avantages,30/06/2023,CA IDF,REMISE CHQ 5065776,REM CH,0.0,NaN,11950.47,-11950.47,7,79,791,7910,79100,349,7,Transferts de charges exceptionnelles,797
586217,34816,791000,Indemnités et avantages,25/07/2023,CA IDF,REM CH 5066216,NaN,0.0,NaN,3880.00,-15830.47,7,79,791,7910,79100,346,7,Transferts de charges,NaN
586218,34816,791000,Indemnités et avantages,25/07/2023,CA IDF,REM CH 5066216,NaN,0.0,NaN,3880.00,-15830.47,7,79,791,7910,79100,347,7,Transferts de charges d'exploitation,791
586219,34816,791000,Indemnités et avantages,25/07/2023,CA IDF,REM CH 5066216,NaN,0.0,NaN,3880.00,-15830.47,7,79,791,7910,79100,348,7,Transferts de charges financières,796
586220,34816,791000,Indemnités et avantages,25/07/2023,CA IDF,REM CH 5066216,NaN,0.0,NaN,3880.00,-15830.47,7,79,791,7910,79100,349,7,Transferts de charges exceptionnelles,797

In [16]:
dfdisplay = df.groupby('niveau1')[['Débit','Crédit']].sum().applymap(int)
dft = dfdisplay.reset_index()
dft.merge(dfnom[dfnom['niveau2'].isna()],on='niveau1')

C:\Users\lvolat\AppData\Local\Temp\ipykernel_12088\4114314948.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dfdisplay = df.groupby('niveau1')[['Débit','Crédit']].sum().applymap(int)

,niveau1,Débit,Crédit,index,Classe,description,niveau2
0,10,0,336600,1,1,Capital et réserves,NaN
1,11,760712,388657,10,1,Report à nouveau (solde créditeur ou débiteur),NaN
2,12,388657,388657,13,1,Résultat de l'exercice (bénéfice ou perte),NaN
3,15,18626,18626,28,1,Provisions,NaN
4,16,896004,2692879,36,1,Emprunts et dettes assimilées,NaN
5,20,490736,0,56,2,Immobilisations incorporelles,NaN
6,21,3766115,22922,61,2,Immobilisations corporelles,NaN
7,27,162177,0,81,2,Autres immobilisations financières,NaN
8,28,5302,2029541,91,2,Amortissements des immobilisations,NaN
9,31,186690,99389,103,3,Matières premières (et fournitures),NaN
10,40,170342,172964,134,4,Fournisseurs et comptes rattachés,NaN
11,41,5206,5206,137,4,Clients et comptes rattachés,NaN
12,42,807905,1022090,140,4,Personnel et comptes rattachés,NaN
13,43,2234976,2548480,148,4,Sécurité sociale et autres organismes sociaux,NaN
14,44,3662522,3735873,152,4,État et autres collectivités publiques,NaN
15,45,2941823,2654175,162,4,Groupe et associés,NaN
16,47,1570,1570,174,4,Comptes transitoires ou d'attente,NaN
17,48,6964,4030,183,4,Comptes de régularisation,NaN
18,51,16701270,16251254,203,5,"Banques, établissements financiers et assimilés",NaN
19,53,1737526,1540864,217,5,Caisse,NaN
20,58,1418941,1418941,222,5,Virements internes,NaN
21,60,2345673,154643,226,6,Achats (sauf 603),NaN
22,61,667284,10733,239,6,Services extérieurs,NaN
23,62,389449,10580,249,6,Autres services extérieurs,NaN
24,63,121305,7212,259,6,"Impôts, taxes et versements assimilés",NaN
25,64,3679313,113632,264,6,Charges de personnel,NaN
26,65,10830,0,271,6,Autres charges de gestion courante,NaN
27,66,40892,0,278,6,Charges financières,NaN
28,67,109451,0,285,6,Charges exceptionnelles,NaN
29,68,356528,0,291,6,"Dotations aux amortissements, aux dépréciation...",NaN
30,70,1000361,8815974,302,7,"Ventes de produits fabriqués, prestations de s...",NaN
31,75,0,21474,318,7,Autres produits de gestion courante,NaN
32,76,0,13491,326,7,Produits financiers,NaN
33,77,0,6513,335,7,Produits exceptionnels,NaN
34,78,0,18626,342,7,"Reprises sur amortissements, dépréciations et ...",NaN
35,79,20894,36725,346,7,Transferts de charges,NaN

In [17]:
import xlsxwriter

workbook = xlsxwriter.Workbook('hello.xlsx')
worksheet = workbook.add_worksheet()

worksheet.write('A1', 'Hello world')

workbook.close()