In [1]:
from cocoAI.FEC import main
from common.path import DATA_PATH

excel_path_list = list(DATA_PATH.glob("202*xls*"))[:2]
main(excel_path_list)

logfile available C:\Users\lvolat\Documents\cocoAI\cocoAI\ipykernel_launcher.log
 Bilan :
           Catégorie      Montant
0            Actifs  14442332.82
1           Passifs  23036481.06
2  Capitaux Propres   3825419.52
3       Total Bilan  -8594148.24

 Compte de Résultat :
       Catégorie     Montant
0      Produits  8912805.87
1       Charges  7720730.50
2  Résultat Net  1192075.37

 Tableau de Flux de Trésorerie :
                  Catégorie     Montant
0       Flux Opérationnels  -467621.59
1     Flux Investissements  2371867.93
2        Flux Financements  1114741.65
3  Variation de Trésorerie  3018987.99

 Présentation Beamer générée : presentation_beamer.tex

In [2]:
from cocoAI.FEC import load_excel_data, load_nomenclature


excel_path_list = list(DATA_PATH.glob("202*xls*"))[:2]
df = load_excel_data(excel_path_list)
df = df.reset_index()
dfnom = load_nomenclature()
dfnom = dfnom.reset_index()

# main(excel_path_list)

cocoAI - INFO - C:\Users\lvolat\Documents\cocoAI\common\nomenclature.yaml loaded

In [3]:
df['Classe'] = df['Compte'].apply(lambda x:str(x)[:1])
df['niveau1'] = df['Compte'].apply(lambda x:str(x)[:2])
df['niveau2'] = df['Compte'].apply(lambda x:str(x)[:3])
df['niveau3'] = df['Compte'].apply(lambda x:str(x)[:4])
df['niveau4'] = df['Compte'].apply(lambda x:str(x)[:5])
dft = df.merge(dfnom,on='niveau1')

In [4]:
dft

,index_x,Compte,Intitulé,Date,Journal,Libellé,Rèf pièce,Débit,Let.,Crédit,Solde,Classe_x,niveau1,niveau2_x,niveau3,niveau4,index_y,Classe_y,description,niveau2_y
0,4,101300,Cap.souscr. appele verse,01/01/2022,AN,REPRISE A NOUVEAU,NaN,0.0,NaN,153000.00,-153000.00,1,10,101,1013,10130,1,1,Capital et réserves,NaN
1,4,101300,Cap.souscr. appele verse,01/01/2022,AN,REPRISE A NOUVEAU,NaN,0.0,NaN,153000.00,-153000.00,1,10,101,1013,10130,2,1,Capital,101
2,4,101300,Cap.souscr. appele verse,01/01/2022,AN,REPRISE A NOUVEAU,NaN,0.0,NaN,153000.00,-153000.00,1,10,101,1013,10130,3,1,Fonds fiduciaires,102
3,4,101300,Cap.souscr. appele verse,01/01/2022,AN,REPRISE A NOUVEAU,NaN,0.0,NaN,153000.00,-153000.00,1,10,101,1013,10130,4,1,Primes liées au capital social,104
4,4,101300,Cap.souscr. appele verse,01/01/2022,AN,REPRISE A NOUVEAU,NaN,0.0,NaN,153000.00,-153000.00,1,10,101,1013,10130,5,1,Écarts de réévaluation,105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586216,34815,791000,Indemnités et avantages,30/06/2023,CA IDF,REMISE CHQ 5065776,REM CH,0.0,NaN,11950.47,-11950.47,7,79,791,7910,79100,349,7,Transferts de charges exceptionnelles,797
586217,34816,791000,Indemnités et avantages,25/07/2023,CA IDF,REM CH 5066216,NaN,0.0,NaN,3880.00,-15830.47,7,79,791,7910,79100,346,7,Transferts de charges,NaN
586218,34816,791000,Indemnités et avantages,25/07/2023,CA IDF,REM CH 5066216,NaN,0.0,NaN,3880.00,-15830.47,7,79,791,7910,79100,347,7,Transferts de charges d'exploitation,791
586219,34816,791000,Indemnités et avantages,25/07/2023,CA IDF,REM CH 5066216,NaN,0.0,NaN,3880.00,-15830.47,7,79,791,7910,79100,348,7,Transferts de charges financières,796
586220,34816,791000,Indemnités et avantages,25/07/2023,CA IDF,REM CH 5066216,NaN,0.0,NaN,3880.00,-15830.47,7,79,791,7910,79100,349,7,Transferts de charges exceptionnelles,797

In [ ]:
dfdisplay = df.groupby('niveau1')[['Débit','Crédit']].sum().applymap(int)
dft = dfdisplay.reset_index()
dft.merge(dfnom[dfnom.niveau2.isna()&dfnom.niveau3.isna()],on='niveau1')

SyntaxError: invalid syntax (2123065242.py, line 3)