In [9]:
from pathlib import Path
import pandas as pd


COCOAI_PATH = Path('c:\\Users\\urnoc\\Documents\\cocoAI')

In [11]:
df = pd.read_csv(COCOAI_PATH/'data/pappers.csv',delimiter=';')

In [12]:
df

,siren,siren_formate,nom_entreprise,personne_morale,denomination,nom,prenom,sexe,siege,villes,...,nb_dirigeants_total,nb_beneficiaires_total,nb_documents_avec_mentions,nb_documents_total,nb_publications_avec_mentions,nb_publications_total,siege_code_postal,Commune,siege_latitude,siege_longitude
0,391251030,391 251 030,ELIODOR,1,ELIODOR,NaN,NaN,NaN,"{""siret"": ""39125103000048"", ""siret_formate"": ""...",ESPELETTE;BONLOC;SAINT PIERRE D'IRUBE;URRUGNE,...,3,1,0,15,0,12,64250,ESPELETTE,NaN,NaN
1,324294735,324 294 735,SAS ANDRIEU,1,SAS ANDRIEU,NaN,NaN,NaN,"{""siret"": ""32429473500349"", ""siret_formate"": ""...",BAYONNE;TOULOUSE;ANGLET;BORDEAUX;LA ROCHELLE;P...,...,5,1,0,22,0,14,64100,BAYONNE,NaN,NaN
2,325645661,325 645 661,MAISON PETRICORENA,1,MAISON PETRICORENA,NaN,NaN,NaN,"{""siret"": ""32564566100019"", ""siret_formate"": ""...",SAINT-ETIENNE-DE-BAIGORRY;ARCANGUES,...,1,2,0,1,0,9,64430,SAINT-ETIENNE-DE-BAIGORRY,NaN,NaN
3,750199390,750 199 390,CHARLY RESTAURATION,1,CHARLY RESTAURATION,NaN,NaN,NaN,"{""siret"": ""75019939000048"", ""siret_formate"": ""...",NaN,...,2,0,0,1,0,11,64990,VILLEFRANQUE,NaN,NaN
4,420911299,420 911 299,CAUDALIE,1,CAUDALIE,NaN,NaN,NaN,"{""siret"": ""42091129900022"", ""siret_formate"": ""...",BAYONNE;ARBONNE;BIDART,...,1,1,0,1,0,13,64100,BAYONNE,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,424746436,424 746 436,SARL CARAULA,1,SARL CARAULA,NaN,NaN,NaN,"{""siret"": ""42474643600015"", ""siret_formate"": ""...",BAYONNE,...,2,1,0,14,0,14,64100,BAYONNE,NaN,NaN
396,477733331,477 733 331,ZAMORA ALAIN,0,NaN,ZAMORA,ALAIN,M,"{""siret"": ""47773333100011"", ""siret_formate"": ""...",GUICHE;ANGLET,...,0,0,0,0,0,0,64520,GUICHE,NaN,NaN
397,499708568,499 708 568,EXILARD JEROME,0,NaN,EXILARD,JEROME,M,"{""siret"": ""49970856800021"", ""siret_formate"": ""...",UHART-MIXE,...,0,0,0,0,0,1,64120,UHART-MIXE,NaN,NaN
398,682711429,682 711 429,SOLORZANO JEAN,0,NaN,SOLORZANO,JEAN,M,"{""siret"": ""68271142900048"", ""siret_formate"": ""...",URRUGNE;SAINT-JEAN-DE-LUZ,...,0,0,0,0,0,1,64122,URRUGNE,NaN,NaN
399,419150859,419 150 859,HIERE JEAN-PAUL,0,NaN,HIERE,JEAN-PAUL,M,"{""siret"": ""41915085900017"", ""siret_formate"": ""...",SENAC;ANGLET;BIDACHE,...,0,0,0,0,0,0,65140,SENAC,NaN,NaN