In [1]:
from pathlib import Path
from mistralai import Mistral
import os

from common.keys import MISTRAL_API_KEY_PAYANTE
from common.path import COMMERCIAL_ONE_DRIVE_PATH, rapatrie_file

client = Mistral(api_key=MISTRAL_API_KEY_PAYANTE)

# CHIEN_QUI_FUME_PATH = (
#     COMMERCIAL_ONE_DRIVE_PATH
#     / "2 - DOSSIERS Ã  l'ETUDE"
#     / "CHIEN QUI FUME (Le) - 75001 PARIS - 33 Rue du PONT-NEUF"
# )

pdf_path = Path(r"C:\Users\lvolat\Desktop\Echeancier def 240507 MAISON MULOT SAS.pdf")



pdf_file_path = rapatrie_file(pdf_path)

logfile available C:\Users\lvolat\Documents\cocoAI\use_cases\ipykernel_launcher.log

cocoAI - INFO - Echeancier def 240507 MAISON MULOT SAS.pdf already exists in data

In [2]:

uploaded_pdf = client.files.upload(
    file={
        "file_name": pdf_file_path.name,
        "content": open(pdf_file_path, "rb"),
    },
    purpose="ocr"
)

In [3]:
client.files.retrieve(file_id=uploaded_pdf.id)

RetrieveFileOut(id='1822ef4a-9ab0-4e01-abbd-2bd3302b2041', object='file', size_bytes=1460828, created_at=1742576431, filename='Echeancier_def_240507_MAISON_MULOT_SAS.pdf', purpose='ocr', sample_type='ocr_input', source='upload', deleted=False, num_lines=None)

In [4]:
signed_url = client.files.get_signed_url(file_id=uploaded_pdf.id)

In [5]:
from mistralai import Mistral
client = Mistral(api_key=MISTRAL_API_KEY_PAYANTE)
ocr_response = client.ocr.process(
    model="mistral-ocr-latest",
    document={
        "type": "document_url",
        "document_url": signed_url.url,
    }
)

In [6]:
import json

response_dict = json.loads(ocr_response.model_dump_json())
print(json.dumps(response_dict, indent=4))  # check the first 1000 characters

{
    "pages": [
        {
            "index": 0,
            "markdown": "# \u00c9ch\u00e9ancier \n\nFHB\n176 Avenue Charles de Gaulle 92200 Neuilly-sur-Seine\n\n12683 SAS MAISON MULOT 76 rue de Seine 75006 PARIS En Commissariat au Plan de Continuation Ouverture: 30/04/2024\n\n27/05/2024\ntribunal de commerce de Paris\nJuge-Commissaire : Jean-Louis GRUTER\nProfessionnel : H\u00e9l\u00e8ne BOURBOULCUX\n$N^{\\circ}$ greffe : P202201532\n12 modifications de RIB depuis 1 an\n(91 cr\u00e9ances trouv\u00e9es)\n\n| $\\mathrm{N}^{\\circ}$ | Cr\u00e9ancier $($ ) | Total | 0 | 0 | $\\begin{gathered} 1 \\\\ 04 / 25 \\end{gathered}$ | $\\begin{gathered} 2 \\\\ 04 / 26 \\end{gathered}$ | $\\begin{gathered} 3 \\\\ 04 / 27 \\end{gathered}$ | $\\begin{gathered} 4 \\\\ 04 / 28 \\end{gathered}$ | $\\begin{gathered} 5 \\\\ 04 / 29 \\end{gathered}$ | $\\begin{gathered} 6 \\\\ 04 / 30 \\end{gathered}$ | $\\begin{gathered} 7 \\\\ 04 / 31 \\end{gathered}$ | $\\begin{gathered} 8 \\\\ 04 / 32 \\end{gathered}$ | $\\begin{gathered} 9 \\\\ 04 / 33 \\end{gathered}$ | $\\begin{gathered} 10 \\\\ 04 / 35 \\end{gathered}$ |\n| :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: |\n| 1 | AG2R LA MONDIALE | 51527,79 | 2 |  | 515,28 | 515,28 | 2576,39 | 2576,39 | 2576,39 | 5152,78 | 5152,78 | 5152,78 | 5152,78 | 22156,94 |\n| 64 | AG2R LA MONDIALE | 11247,15 | 2 | 0 | 112,47 | 112,47 | 562,36 | 562,36 | 562,36 | 1124,72 | 1124,72 | 1124,72 | 1124,72 | 4836,25 |\n| 65 | AG2R LA MONDIALE | 12177,78 | 2 | 0 | 121,78 | 121,78 | 608,89 | 608,89 | 608,89 | 1217,77 | 1217,77 | 1217,77 | 1217,77 | 5236,39 |\n| 6 | AG2R LA MONDIALE PREVUYANCE | 16174,64 | 2 | 0 | 161,75 | 161,75 | 808,73 | 808,73 | 808,73 | 1617,46 | 1617,46 | 1617,46 | 1617,46 | 6955,11 |\n| 66 | AGENCE NADIA CYRILLE | 3596,40 | 2 |  | 35,96 | 35,96 | 179,82 | 179,82 | 179,82 | 359,64 | 359,64 | 359,64 | 359,64 | 1546,46 |\n| 2 | AQUITANIA | 832,80 | 1 |  | 33,31 | 99,94 | 133,25 | 166,56 | 166,56 | 233,18 | 0 | 0 | 0 | 0 |\n| $67$ | BANQUE POPULAIRE A \u00e9choir : 10540,87 | 11989,79 | 2 |  | 119,90 | 119,90 | 599,49 | 599,49 | 599,49 | 1198,98 | 1198,98 | 1198,98 | 1198,98 | 5155,60 |\n| 68 | BANQUE POPULAIRE A \u00e9choir : 331862,24 | 362367,832 |  | 0 | 3623,68 | 3623,68 | 18118,40 | 18118,40 | 18118,40 | 36236,79 | 36236,79 | 36236,79 | 36236,79 | 155818,21 |\n| 69 | BANQUE POPULAIRE A \u00e9choir : 7692,77 | 8942,57 | 2 | 0 | 89,43 | 89,43 | 447,13 | 447,13 | 447,13 | 894,26 | 894,26 | 894,26 | 894,26 | 3845,28 |\n| 70 | BANQUE POPULAIRE | 935,24 | 2 |  | 9,35 | 9,35 | 46,76 | 46,76 | 46,76 | 93,52 | 93,52 | 93,52 | 93,52 | 402,18 |\n| 71 | BANQUE POPULAIRE A \u00e9choir : 7390,70 | 7949,46 | 2 | 0 | 79,49 | 79,49 | 397,47 | 397,47 | 397,47 | 794,95 | 794,95 | 794,95 | 794,95 | 3418,27 |\n| 72 | BANQUE POPULAIRE A \u00e9choir : 6611,34 | 8610,22 | 2 | 0 | 86,10 | 86,10 | 430,51 | 430,51 | 430,51 | 861,02 | 861,02 | 861,02 | 861,02 | 3702,41 |\n| 73 | BANQUE POPULAIRE A \u00e9choir : 7692,77 | 9873,44 | 2 | 0 | 98,73 | 98,73 | 493,67 | 493,67 | 493,67 | 987,34 | 987,34 | 987,34 | 987,34 | 4245,61 |\n| 74 | BANQUE POPULAIRE A \u00e9choir : 19765,88 | 23193,32 | 2 | 0 | 231,93 | 231,93 | 1159,67 | 1159,67 | 1159,67 | 2319,33 | 2319,33 | 2319,33 | 2319,33 | 9973,13 |\n| 3 | BHARLEV INDUSTRIES | 282,43 | 0 | 282,43 |  |  |  |  |  |  |  |  |  |  |\n|  | BMW FINANCE <br> Milt : DURAULT-BIR 8 | 0,00 |  |  | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |\n| 75 | ASSOCI\u00c9S <br> A \u00e9choir : 9693,16 <br> Context: 107,64 |  |  |  |  |  |  |  |  |  |  |  |  |  |\n| 4 | BRISAD | 272,25 | 1 |  | 10,89 | 32,67 | 43,56 | 54,45 | 54,45 | 76,23 | 0 | 0 | 0 | 0 |\n| 5 | CABIS | 4248,57 | 2 |  | 42,49 | 42,49 | 212,43 | 212,43 | 212,43 | 424,86 | 424,86 | 424,86 | 424,86 | 1826,86 |\n| 76 | CAFE SAN JOSE | 1048,48 | 1 |  | 41,94 | 125,82 | 167,76 | 209,70 | 209,70 | 293,56 | 0 | 0 | 0 | 0 |\n| 77 | CANET <br> Context: 9712,12 | 0,00 | 1 |  | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |\n| 9 | CGEA IDF OUEST UNEIDC AGS | 13388,56 | 2 |  | 133,89 | 133,89 | 669,43 | 669,43 | 669,43 | 1338,86 | 1338,86 | 1338,86 | 1338,86 | 5757,05 |\n| 10 | CHOCOLATERIE COLAS | 7844,71 | 1 |  | 313,79 | 941,37 | 1255,15 | 1568,94 | 1568,94 | 2196,52 | 0 | 0 | 0 | 0 |\n| 78 | CHOCOLATERIE DE LOFERA | 5558,45 | 1 | 0 | 222,34 | 667,01 | 889,35 | 1111,69 | 1111,69 | 1556,37 | 0 | 0 | 0 | 0 |\n| 11 | CONSOMAG | 926,40 | 2 |  | 9,26 | 9,26 | 46,32 | 46,32 | 46,32 | 92,64 | 92,64 | 92,64 | 92,64 | 398,36 |\n| 79 | CONSUITING UP | 1528,80 | 1 | 0 | 61,15 | 183,46 | 244,61 | 305,76 | 305,76 | 428,06 | 0 | 0 | 0 | 0 |\n| 12 | CULLIGAN | 346,66 | 0 | 346,66 |  |  |  |  |  |  |  |  |  |  |\n| 80 | DELICE ET CREATION <br> Milt : EULER HERMES | 9702,85 | 2 | 0 | 97,03 | 97,03 | 485,14 | 485,14 | 485,14 | 970,29 | 970,29 | 970,29 | 970,29 | 4172,21 |\n| 13 | DEROCHE | 5566,79 | 2 |  | 55,67 | 55,67 | 278,34 | 278,34 | 278,34 | 556,68 | 556,68 | 556,68 | 556,68 | 2393,71 |\n| 14 | DIDIER \\& LEVY | 543,00 | 1 |  | 21,72 | 65,16 | 86,88 | 108,60 | 108,60 | 152,04 | 0 | 0 | 0 | 0 |\n| 81 | DIPSA <br> Milt : EULER HERMES | 9890,00 | 2 | 0 | 98,90 | 98,90 | 494,50 | 494,50 | 494,50 | 989,00 | 989,00 | 989,00 | 989,00 | 4252,70 |\n| 82 | DIFFIF ILE DE FRANCE ET PARIS | 6672,42 | 2 |  | 66,72 | 66,72 | 333,62 | 333,62 | 333,62 | 667,24 | 667,24 | 667,24 | 667,24 | 2869,16 |\n| 15 | EAU DE PARIS | 1721,22 | 2 |  | 17,21 | 17,21 | 86,06 | 86,06 | 86,06 | 172,12 | 172,12 | 172,12 | 172,12 | 740,14 |\n| 16 | ENGIE <br> Milt : ENGIE | 666,74 | 1 |  | 26,67 | 80,01 | 106,68 | 133,35 | 133,35 | 186,68 | 0 | 0 | 0 | 0 |\n| 17 | ENGIE <br> Milt : ENGIE | 501,96 | 1 |  | 20,08 | 60,24 | 80,31 | 100,39 | 100,39 | 140,55 | 0 | 0 | 0 | 0 |\n| 18 | PESTIN DE BOURGOONE | 10572,77 | 2 |  | 105,73 | 105,73 | 528,64 | 528,64 | 528,64 | 1057,28 | 1057,28 | 1057,28 | 1057,28 | 4546,27 |\n| 83 | PIDUCIAL INFORMATION | 0,00 | 0 | 0 |  |  |  |  |  |  |  |  |  |  |\n| 84 | PIDUCIAL <br> INFORMATION | 1143,32 | 2 |  | 11,43 | 11,43 | 57,17 | 57,17 | 57,17 | 114,33 | 114,33 | 114,33 | 114,33 | 491,63 |\n| 19 | GAMME DES CHEFS PARIS | 5711,79 | 2 |  | 57,12 | 57,12 | 285,59 | 285,59 | 285,59 | 571,18 | 571,18 | 571,18 | 571,18 | 2456,06 |\n| 20 | GARBATT | 12065,03 | 2 |  | 120,65 | 120,65 | 603,25 | 603,25 | 603,25 | 1206,50 | 1206,50 | 1206,50 | 1206,50 | 5187,98 |\n| 85 | GUIMARHIAL <br> Milt : CARINET BAP | 3429,02 | 2 |  | 34,29 | 34,29 | 171,45 | 171,45 | 171,45 | 342,90 | 342,90 | 342,90 | 342,90 | 1474,49 |\n| 22 | HPS J.COLAS ET CIE | 21847,48 | 1 |  | 873,90 | 2621,70 | 3495,60 | 4369,50 | 4369,50 | 6117,28 | 0 | 0 | 0 | 0 |",
            "images": [],
            "dimensions": {
                "dpi": 200,
                "height": 2339,
                "width": 1654
            }
        },
        {
            "index": 1,
            "markdown": "![img-0.jpeg](img-0.jpeg)",
            "images": [
                {
                    "id": "img-0.jpeg",
                    "top_left_x": 82,
                    "top_left_y": 56,
                    "bottom_right_x": 1586,
                    "bottom_right_y": 2156,
                    "image_base64": null
                }
            ],
            "dimensions": {
                "dpi": 200,
                "height": 2339,
                "width": 1654
            }
        }
    ],
    "model": "mistral-ocr-2503-completion",
    "usage_info": {
        "pages_processed": 2,
        "doc_size_bytes": 1460828
    }
}

In [7]:
from IPython.display import Markdown, display
display(Markdown(response_dict['pages'][0]['markdown']))

# ÃchÃ©ancier

FHB
176 Avenue Charles de Gaulle 92200 Neuilly-sur-Seine

12683 SAS MAISON MULOT 76 rue de Seine 75006 PARIS En Commissariat au Plan de Continuation Ouverture: 30/04/2024

27/05/2024
tribunal de commerce de Paris
Juge-Commissaire : Jean-Louis GRUTER
Professionnel : HÃ©lÃ¨ne BOURBOULCUX
$N^{\circ}$ greffe : P202201532
12 modifications de RIB depuis 1 an
(91 crÃ©ances trouvÃ©es)

| $\mathrm{N}^{\circ}$ | CrÃ©ancier $($ ) | Total | 0 | 0 | $\begin{gathered} 1 \\ 04 / 25 \end{gathered}$ | $\begin{gathered} 2 \\ 04 / 26 \end{gathered}$ | $\begin{gathered} 3 \\ 04 / 27 \end{gathered}$ | $\begin{gathered} 4 \\ 04 / 28 \end{gathered}$ | $\begin{gathered} 5 \\ 04 / 29 \end{gathered}$ | $\begin{gathered} 6 \\ 04 / 30 \end{gathered}$ | $\begin{gathered} 7 \\ 04 / 31 \end{gathered}$ | $\begin{gathered} 8 \\ 04 / 32 \end{gathered}$ | $\begin{gathered} 9 \\ 04 / 33 \end{gathered}$ | $\begin{gathered} 10 \\ 04 / 35 \end{gathered}$ |
| :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: |
| 1 | AG2R LA MONDIALE | 51527,79 | 2 |  | 515,28 | 515,28 | 2576,39 | 2576,39 | 2576,39 | 5152,78 | 5152,78 | 5152,78 | 5152,78 | 22156,94 |
| 64 | AG2R LA MONDIALE | 11247,15 | 2 | 0 | 112,47 | 112,47 | 562,36 | 562,36 | 562,36 | 1124,72 | 1124,72 | 1124,72 | 1124,72 | 4836,25 |
| 65 | AG2R LA MONDIALE | 12177,78 | 2 | 0 | 121,78 | 121,78 | 608,89 | 608,89 | 608,89 | 1217,77 | 1217,77 | 1217,77 | 1217,77 | 5236,39 |
| 6 | AG2R LA MONDIALE PREVUYANCE | 16174,64 | 2 | 0 | 161,75 | 161,75 | 808,73 | 808,73 | 808,73 | 1617,46 | 1617,46 | 1617,46 | 1617,46 | 6955,11 |
| 66 | AGENCE NADIA CYRILLE | 3596,40 | 2 |  | 35,96 | 35,96 | 179,82 | 179,82 | 179,82 | 359,64 | 359,64 | 359,64 | 359,64 | 1546,46 |
| 2 | AQUITANIA | 832,80 | 1 |  | 33,31 | 99,94 | 133,25 | 166,56 | 166,56 | 233,18 | 0 | 0 | 0 | 0 |
| $67$ | BANQUE POPULAIRE A Ã©choir : 10540,87 | 11989,79 | 2 |  | 119,90 | 119,90 | 599,49 | 599,49 | 599,49 | 1198,98 | 1198,98 | 1198,98 | 1198,98 | 5155,60 |
| 68 | BANQUE POPULAIRE A Ã©choir : 331862,24 | 362367,832 |  | 0 | 3623,68 | 3623,68 | 18118,40 | 18118,40 | 18118,40 | 36236,79 | 36236,79 | 36236,79 | 36236,79 | 155818,21 |
| 69 | BANQUE POPULAIRE A Ã©choir : 7692,77 | 8942,57 | 2 | 0 | 89,43 | 89,43 | 447,13 | 447,13 | 447,13 | 894,26 | 894,26 | 894,26 | 894,26 | 3845,28 |
| 70 | BANQUE POPULAIRE | 935,24 | 2 |  | 9,35 | 9,35 | 46,76 | 46,76 | 46,76 | 93,52 | 93,52 | 93,52 | 93,52 | 402,18 |
| 71 | BANQUE POPULAIRE A Ã©choir : 7390,70 | 7949,46 | 2 | 0 | 79,49 | 79,49 | 397,47 | 397,47 | 397,47 | 794,95 | 794,95 | 794,95 | 794,95 | 3418,27 |
| 72 | BANQUE POPULAIRE A Ã©choir : 6611,34 | 8610,22 | 2 | 0 | 86,10 | 86,10 | 430,51 | 430,51 | 430,51 | 861,02 | 861,02 | 861,02 | 861,02 | 3702,41 |
| 73 | BANQUE POPULAIRE A Ã©choir : 7692,77 | 9873,44 | 2 | 0 | 98,73 | 98,73 | 493,67 | 493,67 | 493,67 | 987,34 | 987,34 | 987,34 | 987,34 | 4245,61 |
| 74 | BANQUE POPULAIRE A Ã©choir : 19765,88 | 23193,32 | 2 | 0 | 231,93 | 231,93 | 1159,67 | 1159,67 | 1159,67 | 2319,33 | 2319,33 | 2319,33 | 2319,33 | 9973,13 |
| 3 | BHARLEV INDUSTRIES | 282,43 | 0 | 282,43 |  |  |  |  |  |  |  |  |  |  |
|  | BMW FINANCE <br> Milt : DURAULT-BIR 8 | 0,00 |  |  | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| 75 | ASSOCIÃS <br> A Ã©choir : 9693,16 <br> Context: 107,64 |  |  |  |  |  |  |  |  |  |  |  |  |  |
| 4 | BRISAD | 272,25 | 1 |  | 10,89 | 32,67 | 43,56 | 54,45 | 54,45 | 76,23 | 0 | 0 | 0 | 0 |
| 5 | CABIS | 4248,57 | 2 |  | 42,49 | 42,49 | 212,43 | 212,43 | 212,43 | 424,86 | 424,86 | 424,86 | 424,86 | 1826,86 |
| 76 | CAFE SAN JOSE | 1048,48 | 1 |  | 41,94 | 125,82 | 167,76 | 209,70 | 209,70 | 293,56 | 0 | 0 | 0 | 0 |
| 77 | CANET <br> Context: 9712,12 | 0,00 | 1 |  | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| 9 | CGEA IDF OUEST UNEIDC AGS | 13388,56 | 2 |  | 133,89 | 133,89 | 669,43 | 669,43 | 669,43 | 1338,86 | 1338,86 | 1338,86 | 1338,86 | 5757,05 |
| 10 | CHOCOLATERIE COLAS | 7844,71 | 1 |  | 313,79 | 941,37 | 1255,15 | 1568,94 | 1568,94 | 2196,52 | 0 | 0 | 0 | 0 |
| 78 | CHOCOLATERIE DE LOFERA | 5558,45 | 1 | 0 | 222,34 | 667,01 | 889,35 | 1111,69 | 1111,69 | 1556,37 | 0 | 0 | 0 | 0 |
| 11 | CONSOMAG | 926,40 | 2 |  | 9,26 | 9,26 | 46,32 | 46,32 | 46,32 | 92,64 | 92,64 | 92,64 | 92,64 | 398,36 |
| 79 | CONSUITING UP | 1528,80 | 1 | 0 | 61,15 | 183,46 | 244,61 | 305,76 | 305,76 | 428,06 | 0 | 0 | 0 | 0 |
| 12 | CULLIGAN | 346,66 | 0 | 346,66 |  |  |  |  |  |  |  |  |  |  |
| 80 | DELICE ET CREATION <br> Milt : EULER HERMES | 9702,85 | 2 | 0 | 97,03 | 97,03 | 485,14 | 485,14 | 485,14 | 970,29 | 970,29 | 970,29 | 970,29 | 4172,21 |
| 13 | DEROCHE | 5566,79 | 2 |  | 55,67 | 55,67 | 278,34 | 278,34 | 278,34 | 556,68 | 556,68 | 556,68 | 556,68 | 2393,71 |
| 14 | DIDIER \& LEVY | 543,00 | 1 |  | 21,72 | 65,16 | 86,88 | 108,60 | 108,60 | 152,04 | 0 | 0 | 0 | 0 |
| 81 | DIPSA <br> Milt : EULER HERMES | 9890,00 | 2 | 0 | 98,90 | 98,90 | 494,50 | 494,50 | 494,50 | 989,00 | 989,00 | 989,00 | 989,00 | 4252,70 |
| 82 | DIFFIF ILE DE FRANCE ET PARIS | 6672,42 | 2 |  | 66,72 | 66,72 | 333,62 | 333,62 | 333,62 | 667,24 | 667,24 | 667,24 | 667,24 | 2869,16 |
| 15 | EAU DE PARIS | 1721,22 | 2 |  | 17,21 | 17,21 | 86,06 | 86,06 | 86,06 | 172,12 | 172,12 | 172,12 | 172,12 | 740,14 |
| 16 | ENGIE <br> Milt : ENGIE | 666,74 | 1 |  | 26,67 | 80,01 | 106,68 | 133,35 | 133,35 | 186,68 | 0 | 0 | 0 | 0 |
| 17 | ENGIE <br> Milt : ENGIE | 501,96 | 1 |  | 20,08 | 60,24 | 80,31 | 100,39 | 100,39 | 140,55 | 0 | 0 | 0 | 0 |
| 18 | PESTIN DE BOURGOONE | 10572,77 | 2 |  | 105,73 | 105,73 | 528,64 | 528,64 | 528,64 | 1057,28 | 1057,28 | 1057,28 | 1057,28 | 4546,27 |
| 83 | PIDUCIAL INFORMATION | 0,00 | 0 | 0 |  |  |  |  |  |  |  |  |  |  |
| 84 | PIDUCIAL <br> INFORMATION | 1143,32 | 2 |  | 11,43 | 11,43 | 57,17 | 57,17 | 57,17 | 114,33 | 114,33 | 114,33 | 114,33 | 491,63 |
| 19 | GAMME DES CHEFS PARIS | 5711,79 | 2 |  | 57,12 | 57,12 | 285,59 | 285,59 | 285,59 | 571,18 | 571,18 | 571,18 | 571,18 | 2456,06 |
| 20 | GARBATT | 12065,03 | 2 |  | 120,65 | 120,65 | 603,25 | 603,25 | 603,25 | 1206,50 | 1206,50 | 1206,50 | 1206,50 | 5187,98 |
| 85 | GUIMARHIAL <br> Milt : CARINET BAP | 3429,02 | 2 |  | 34,29 | 34,29 | 171,45 | 171,45 | 171,45 | 342,90 | 342,90 | 342,90 | 342,90 | 1474,49 |
| 22 | HPS J.COLAS ET CIE | 21847,48 | 1 |  | 873,90 | 2621,70 | 3495,60 | 4369,50 | 4369,50 | 6117,28 | 0 | 0 | 0 | 0 |

In [8]:
from mistralai import DocumentURLChunk, Mistral, TextChunk

# Get OCR results for processing
ocr_markdown = response_dict["pages"][0]["markdown"]

# Get structured response from model
chat_response = client.chat.complete(
    model="ministral-8b-latest",
    messages=[
        {
            "role": "user",
            "content": [
                TextChunk(
                    text=(
                        f"This is image's OCR in markdown:\n\n{ocr_markdown}\n.\n"
                        "Convert this into a sensible structured json response. "
                        "The output should be strictly be json with no extra commentary."
                        "All the keys must labeled in english"
                    )
                ),
            ],
        }
    ],
    response_format={"type": "json_object"},
    temperature=0,
)

# Parse and return JSON response
response_dict2= json.loads(chat_response.choices[0].message.content)
print(json.dumps(response_dict2, indent=4))

{
    "company": "FHB",
    "address": "176 Avenue Charles de Gaulle 92200 Neuilly-sur-Seine",
    "court": "tribunal de commerce de Paris",
    "judge": "Jean-Louis GRUTER",
    "professional": "H\u00e9l\u00e8ne BOURBOULCUX",
    "greffe": "P202201532",
    "modifications": 12,
    "creditors": [
        {
            "number": 1,
            "creditor": "AG2R LA MONDIALE",
            "total": 51527.79,
            "payments": [
                2,
                515.28,
                2576.39,
                5152.78,
                22156.94
            ]
        },
        {
            "number": 64,
            "creditor": "AG2R LA MONDIALE",
            "total": 11247.15,
            "payments": [
                2,
                112.47,
                562.36,
                1124.72,
                4836.25
            ]
        },
        {
            "number": 65,
            "creditor": "AG2R LA MONDIALE",
            "total": 12177.78,
            "payments": [
                2,
                121.78,
                608.89,
                1217.77,
                5236.39
            ]
        },
        {
            "number": 6,
            "creditor": "AG2R LA MONDIALE PREVUYANCE",
            "total": 16174.64,
            "payments": [
                2,
                161.75,
                808.73,
                1617.46,
                6955.11
            ]
        },
        {
            "number": 66,
            "creditor": "AGENCE NADIA CYRILLE",
            "total": 3596.4,
            "payments": [
                2,
                35.96,
                179.82,
                359.64,
                1546.46
            ]
        },
        {
            "number": 2,
            "creditor": "AQUITANIA",
            "total": 832.8,
            "payments": [
                1,
                33.31,
                133.25,
                166.56,
                233.18
            ]
        },
        {
            "number": 67,
            "creditor": "BANQUE POPULAIRE",
            "total": 11989.79,
            "payments": [
                2,
                119.9,
                599.49,
                1198.98,
                5155.6
            ]
        },
        {
            "number": 68,
            "creditor": "BANQUE POPULAIRE",
            "total": 362367.832,
            "payments": [
                0,
                3623.68,
                18118.4,
                36236.79,
                155818.21
            ]
        },
        {
            "number": 69,
            "creditor": "BANQUE POPULAIRE",
            "total": 8942.57,
            "payments": [
                2,
                89.43,
                447.13,
                894.26,
                3845.28
            ]
        },
        {
            "number": 70,
            "creditor": "BANQUE POPULAIRE",
            "total": 935.24,
            "payments": [
                2,
                9.35,
                46.76,
                93.52,
                402.18
            ]
        },
        {
            "number": 71,
            "creditor": "BANQUE POPULAIRE",
            "total": 7949.46,
            "payments": [
                2,
                79.49,
                397.47,
                794.95,
                3418.27
            ]
        },
        {
            "number": 72,
            "creditor": "BANQUE POPULAIRE",
            "total": 8610.22,
            "payments": [
                2,
                86.1,
                430.51,
                861.02,
                3702.41
            ]
        },
        {
            "number": 73,
            "creditor": "BANQUE POPULAIRE",
            "total": 9873.44,
            "payments": [
                2,
                98.73,
                493.67,
                987.34,
                4245.61
            ]
        },
        {
            "number": 74,
            "creditor": "BANQUE POPULAIRE",
            "total": 23193.32,
            "payments": [
                2,
                231.93,
                1159.67,
                2319.33,
                9973.13
            ]
        },
        {
            "number": 3,
            "creditor": "BHARLEV INDUSTRIES",
            "total": 282.43,
            "payments": [
                0,
                282.43
            ]
        },
        {
            "number": 75,
            "creditor": "ASSOCI\u00c9S",
            "total": 9693.16,
            "payments": [
                0,
                0,
                0,
                0,
                0
            ]
        },
        {
            "number": 4,
            "creditor": "BRISAD",
            "total": 272.25,
            "payments": [
                1,
                10.89,
                32.67,
                43.56,
                54.45,
                76.23
            ]
        },
        {
            "number": 5,
            "creditor": "CABIS",
            "total": 4248.57,
            "payments": [
                2,
                42.49,
                212.43,
                424.86,
                1826.86
            ]
        },
        {
            "number": 76,
            "creditor": "CAFE SAN JOSE",
            "total": 1048.48,
            "payments": [
                1,
                41.94,
                125.82,
                167.76,
                209.7,
                293.56
            ]
        },
        {
            "number": 77,
            "creditor": "CANET",
            "total": 0,
            "payments": [
                1,
                0,
                0,
                0,
                0,
                0
            ]
        },
        {
            "number": 9,
            "creditor": "CGEA IDF OUEST UNEIDC AGS",
            "total": 13388.56,
            "payments": [
                2,
                133.89,
                669.43,
                1338.86,
                5757.05
            ]
        },
        {
            "number": 10,
            "creditor": "CHOCOLATERIE COLAS",
            "total": 7844.71,
            "payments": [
                1,
                313.79,
                941.37,
                1255.15,
                1568.94,
                2196.52
            ]
        },
        {
            "number": 78,
            "creditor": "CHOCOLATERIE DE LOFERA",
            "total": 5558.45,
            "payments": [
                1,
                222.34,
                667.01,
                889.35,
                1111.69,
                1556.37
            ]
        },
        {
            "number": 11,
            "creditor": "CONSOMAG",
            "total": 926.4,
            "payments": [
                2,
                9.26,
                46.32,
                92.64,
                398.36
            ]
        },
        {
            "number": 79,
            "creditor": "CONSUITING UP",
            "total": 1528.8,
            "payments": [
                1,
                61.15,
                183.46,
                244.61,
                305.76,
                428.06
            ]
        },
        {
            "number": 12,
            "creditor": "CULLIGAN",
            "total": 346.66,
            "payments": [
                0,
                346.66
            ]
        },
        {
            "number": 80,
            "creditor": "DELICE ET CREATION",
            "total": 9702.85,
            "payments": [
                2,
                97.03,
                485.14,
                970.29,
                4172.21
            ]
        },
        {
            "number": 13,
            "creditor": "DEROCHE",
            "total": 5566.79,
            "payments": [
                2,
                55.67,
                278.34,
                556.68,
                2393.71
            ]
        },
        {
            "number": 14,
            "creditor": "DIDIER & LEVY",
            "total": 543.0,
            "payments": [
                1,
                21.72,
                65.16,
                86.88,
                108.6,
                152.04
            ]
        },
        {
            "number": 81,
            "creditor": "DIPSA",
            "total": 9890.0,
            "payments": [
                2,
                98.9,
                494.5,
                989.0,
                4252.7
            ]
        },
        {
            "number": 82,
            "creditor": "DIFFIF ILE DE FRANCE ET PARIS",
            "total": 6672.42,
            "payments": [
                2,
                66.72,
                333.62,
                667.24,
                2869.16
            ]
        },
        {
            "number": 15,
            "creditor": "EAU DE PARIS",
            "total": 1721.22,
            "payments": [
                2,
                17.21,
                86.06,
                172.12,
                740.14
            ]
        },
        {
            "number": 16,
            "creditor": "ENGIE",
            "total": 666.74,
            "payments": [
                1,
                26.67,
                80.01,
                106.68,
                133.35,
                186.68
            ]
        },
        {
            "number": 17,
            "creditor": "ENGIE",
            "total": 501.96,
            "payments": [
                1,
                20.08,
                60.24,
                80.31,
                100.39,
                140.55
            ]
        },
        {
            "number": 18,
            "creditor": "PESTIN DE BOURGOONE",
            "total": 10572.77,
            "payments": [
                2,
                105.73,
                528.64,
                1057.28,
                4546.27
            ]
        },
        {
            "number": 83,
            "creditor": "PIDUCIAL INFORMATION",
            "total": 0,
            "payments": [
                0,
                0,
                0,
                0,
                0
            ]
        },
        {
            "number": 84,
            "creditor": "PIDUCIAL",
            "total": 1143.32,
            "payments": [
                2,
                11.43,
                57.17,
                114.33,
                491.63
            ]
        },
        {
            "number": 19,
            "creditor": "GAMME DES CHEFS PARIS",
            "total": 5711.79,
            "payments": [
                2,
                57.12,
                285.59,
                571.18,
                2456.06
            ]
        },
        {
            "number": 20,
            "creditor": "GARBATT",
            "total": 12065.03,
            "payments": [
                2,
                120.65,
                603.25,
                1206.5,
                5187.98
            ]
        },
        {
            "number": 85,
            "creditor": "GUIMARHIAL",
            "total": 3429.02,
            "payments": [
                2,
                34.29,
                171.45,
                342.9,
                1474.49
            ]
        },
        {
            "number": 22,
            "creditor": "HPS J.COLAS ET CIE",
            "total": 21847.48,
            "payments": [
                1,
                873.9,
                2621.7,
                3495.6,
                4369.5,
                6117.28
            ]
        }
    ]
}

In [21]:
import pandas as pd 
df = pd.json_normalize(response_dict2['creditors'],max_level=1).explode('payments').reset_index()
df

     index  number            creditor     total  payments
0        0       1    AG2R LA MONDIALE  51527.79         2
1        0       1    AG2R LA MONDIALE  51527.79    515.28
2        0       1    AG2R LA MONDIALE  51527.79   2576.39
3        0       1    AG2R LA MONDIALE  51527.79   5152.78
4        0       1    AG2R LA MONDIALE  51527.79  22156.94
..     ...     ...                 ...       ...       ...
204     40      22  HPS J.COLAS ET CIE  21847.48     873.9
205     40      22  HPS J.COLAS ET CIE  21847.48    2621.7
206     40      22  HPS J.COLAS ET CIE  21847.48    3495.6
207     40      22  HPS J.COLAS ET CIE  21847.48    4369.5
208     40      22  HPS J.COLAS ET CIE  21847.48   6117.28

[209 rows x 5 columns]

In [19]:
# df['no_echeance'] = df['payments'].apply(lambda x:x['date'])
# df['amount'] = df['payments'].apply(lambda x:float(x['amount']))
# df = df.drop('payments',axis=1)
df = df.pivot(index=['number','creditor','total'],columns=['payments'])
df.to_excel('Echeancier_Mulot.xlsx')

ValueError: Index contains duplicate entries, cannot reshape

In [40]:
df

Empty DataFrame
Columns: []
Index: [(1, AG2R LA MONDIALE, 51527.79), (2, AQUITANIA, 832.8), (3, BHARLEV INDUSTRIES, 282.43), (6, AG2R LA MONDIALE PREVUYANCE, 16174.64), (9, CGEA IDF OUEST UNEIDC AGS, 13388.56), (10, CHOCOLATERIE COLAS, 7844.71), (11, CONSOMAG, 926.4), (12, CULLIGAN, 346.66), (13, DEROCHE, 5566.79), (14, DIDIER & LEVY, 543.0), (15, EAU DE PARIS, 1721.22), (16, ENGIE, 666.74), (17, ENGIE, 501.96), (18, PESTIN DE BOURGOONE, 10572.77), (19, GAMME DES CHEFS PARIS, 5711.79), (20, GARBATT, 12065.03), (22, HPS J.COLAS ET CIE, 21847.48), (64, AG2R LA MONDIALE, 11247.15), (65, AG2R LA MONDIALE, 12177.78), (66, AGENCE NADIA CYRILLE, 3596.4), (67, BANQUE POPULAIRE, 11989.79), (68, BANQUE POPULAIRE, 362367.832), (69, BANQUE POPULAIRE, 8942.57), (70, BANQUE POPULAIRE, 935.24), (71, BANQUE POPULAIRE, 7949.46), (72, BANQUE POPULAIRE, 8610.22), (73, BANQUE POPULAIRE, 9873.44), (74, BANQUE POPULAIRE, 23193.32), (78, CHOCOLATERIE DE LOFERA, 5558.45), (79, CONSUITING UP, 1528.8), (80, DELICE ET CREATION, 9702.85), (81, DIPSA, 9890.0), (82, DIFFIF ILE DE FRANCE ET PARIS, 6672.42), (83, PIDUCIAL INFORMATION, 0.0), (84, PIDUCIAL INFORMATION, 1143.32), (85, GUIMARHIAL, 3429.02)]

In [14]:
df.explode('payments').explode('payments')

    number              debtor     total payments
0        1    AG2R LA MONDIALE  51527.79     date
0        1    AG2R LA MONDIALE  51527.79   amount
0        1    AG2R LA MONDIALE  51527.79     date
0        1    AG2R LA MONDIALE  51527.79   amount
0        1    AG2R LA MONDIALE  51527.79     date
..     ...                 ...       ...      ...
35      22  HPS J.COLAS ET CIE  21847.48   amount
35      22  HPS J.COLAS ET CIE  21847.48     date
35      22  HPS J.COLAS ET CIE  21847.48   amount
35      22  HPS J.COLAS ET CIE  21847.48     date
35      22  HPS J.COLAS ET CIE  21847.48   amount

[684 rows x 4 columns]

In [ ]:
display(Markdown(response_dict['pages'][1]['markdown']))

In [ ]:
# Import required libraries
import json

from IPython.display import Markdown, display
from mistralai import DocumentURLChunk, Mistral
from mistralai.models import OCRResponse
def replace_images_in_markdown(markdown_str: str, images_dict: dict) -> str:
    """
    Replace image placeholders in markdown with base64-encoded images.

    Args:
        markdown_str: Markdown text containing image placeholders
        images_dict: Dictionary mapping image IDs to base64 strings

    Returns:
        Markdown text with images replaced by base64 data
    """
    for img_name, base64_str in images_dict.items():
        markdown_str = markdown_str.replace(
            f"![{img_name}]({img_name})", f"![{img_name}]({base64_str})"
        )
    return markdown_str


def get_combined_markdown(ocr_response: OCRResponse) -> str:
    """
    Combine OCR text and images into a single markdown document.

    Args:
        ocr_response: Response from OCR processing containing text and images

    Returns:
        Combined markdown string with embedded images
    """
    markdowns: list[str] = []
    # Extract images from page
    for page in ocr_response.pages:
        image_data = {}
        for img in page.images:
            # print(img)
            # print(type(img))
            # print(img.image_base64)
            image_data[img.id] = img.image_base64
        # Replace image placeholders with actual images
        markdowns.append(replace_images_in_markdown(page.markdown, image_data))

    return "\n\n".join(markdowns)


# Display combined markdowns and images
display(Markdown(get_combined_markdown(ocr_response)))

In [ ]:
# Import required libraries
import json

from IPython.display import Markdown, display
from mistralai import DocumentURLChunk, Mistral
from mistralai.models import OCRResponse
from common.path import COMMERCIAL_ONE_DRIVE_PATH, rapatrie_file


api_key = MISTRAL_API_KEY_PAYANTE  # Replace with your API key
client = Mistral(api_key=api_key)



# Upload PDF file to Mistral's OCR service
uploaded_file = client.files.upload(
    file={
        "file_name": pdf_file_path.stem,
        "content": pdf_file_path.read_bytes(),
    },
    purpose="ocr",
)

# Get URL for the uploaded file
signed_url = client.files.get_signed_url(file_id=uploaded_file.id, expiry=1)

# Process PDF with OCR, including embedded images
pdf_response = client.ocr.process(
    document=DocumentURLChunk(document_url=signed_url.url),
    model="mistral-ocr-latest",
    include_image_base64=True,
)

In [ ]:
display(Markdown(response_dict['pages'][0]['markdown']))

In [ ]:
display(Markdown(response_dict['pages'][1]['markdown']))

In [ ]:
for p in ocr_response.pages:
    print(p.images)

In [ ]:
response_dict['pages'][1]['images']
# .image_base64

In [ ]:
# for page in pdf_response.pages:
#     image_data = {}
#     for img in page.images:
#         print(img)
#         print(type(img))
#         print(img.image_base64)
#         image_data[img.id] = img.image_base64
#         break

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image_url",
                "image_url": response_dict['pages'][1]['images'][0].image_base64,
            },
            {
                "type": "text",
                "text": "Extract the whole table of that image"
            }
        ]
    },
    {"role": "assistant", "content": "{", "prefix": True},
]

# Get the chat response
chat_response = client.chat.complete(
    model="pixtral-large-latest",
    # model="mistral-ocr-latest",
    messages=messages,
    # response_format = {
    #       "type": "json_object",
    # }

)

# Print the content of the response
print(chat_response.choices[0].message.content)

In [ ]:

def replace_images_in_markdown(markdown_str: str, images_dict: dict) -> str:
    """
    Replace image placeholders in markdown with base64-encoded images.

    Args:
        markdown_str: Markdown text containing image placeholders
        images_dict: Dictionary mapping image IDs to base64 strings

    Returns:
        Markdown text with images replaced by base64 data
    """
    for img_name, base64_str in images_dict.items():
        markdown_str = markdown_str.replace(
            f"![{img_name}]({img_name})", f"![{img_name}]({base64_str})"
        )
    return markdown_str


def get_combined_markdown(ocr_response: OCRResponse) -> str:
    """
    Combine OCR text and images into a single markdown document.

    Args:
        ocr_response: Response from OCR processing containing text and images

    Returns:
        Combined markdown string with embedded images
    """
    markdowns: list[str] = []
    # Extract images from page
    for page in ocr_response.pages:
        image_data = {}
        for img in page.images:
            # print(img)
            # print(type(img))
            # print(img.image_base64)
            image_data[img.id] = img.image_base64
        # Replace image placeholders with actual images
        markdowns.append(replace_images_in_markdown(page.markdown, image_data))

    return "\n\n".join(markdowns)


# Display combined markdowns and images
display(Markdown(get_combined_markdown(pdf_response)))

In [ ]:
get_combined_markdown(pdf_response)

In [ ]:
api_key

In [ ]:
img.image_base64

In [ ]:

for page in pdf_response.pages:
    image_data = {}
    for img in page.images:
        print(img)
        print(type(img))
        print(img.image_base64)
        image_data[img.id] = img.image_base64
        break

# client = Mistral(api_key=api_key)

In [ ]:

client = Mistral(api_key=api_key)
base64_image = img.image_base64



ocr_response = client.ocr.process(
    model="mistral-ocr-latest",
document={
        "type": "image_url",
        "image_url": base64_image,
    },
    include_image_base64=True
)

In [ ]:

ocr_response

In [ ]:
# Convert response to JSON format
response_dict = json.loads(ocr_response.model_dump_json())

print(json.dumps(response_dict, indent=4)[0:1000])

In [ ]:
messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image_url",
                "image_url": base64_image,
            },
            {
                "type": "text",
                "text": "Extract the whole table of that image"
            }
        ]
    },
    {"role": "assistant", "content": "{", "prefix": True},
]

# Get the chat response
chat_response = client.chat.complete(
    model="pixtral-large-latest",
    # model="mistral-ocr-latest",
    messages=messages,
    # response_format = {
    #       "type": "json_object",
    # }

)

# Print the content of the response
print(chat_response.choices[0].message.content)

In [ ]:
import pprint
# pprint.pprint(chat_response.choices[0].message.content)
pprint.pprint(chat_response)


cont = chat_response.choices[0].message.content
# pd.read_json(columns=)

In [ ]:
json.cont

In [ ]:
import pandas as pd
df = pd.read_json(cont)

In [ ]:
import pandas as pd
pd.read_json(chat_response.choices[0].message.content)

In [ ]:
import json

with open('ocr_dataset.json', 'w') as f:
    json.dump(ocr_response, f, indent=4)

In [ ]:
pprint(ocr_response)

In [ ]:

# Specify model
model = "mistral-small-latest"

# # Initialize the Mistral client
# client = Mistral(api_key=api_key)

# Define the messages for the chat
messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": "print that table in a markdown format"
            },
        ]
    }
]

# Get the chat response
chat_response = client.chat.complete(
    model=model,
    messages=messages
)

# Print the content of the response
print(chat_response.choices[0].message.content)

In [ ]:
ocr_response

In [ ]:
import os
from mistralai import Mistral

# Retrieve the API key from environment variables
api_key = MISTRAL_API_KEY_PAYANTE

# Specify model
model = "mistral-small-latest"

# Initialize the Mistral client
client = Mistral(api_key=api_key)

# Define the messages for the chat
messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": "quel est le montant des immoblisations incorporelles pour l'exercice 2021?"
                # "text": "quel est le chiffre d'affaires en 2022 ?"
            },
            {
                "type": "document_url",
                "document_url": signed_url.url
            }
        ]
    }
]

# Get the chat response
chat_response = client.chat.complete(
    model=model,
    messages=messages
)

# Print the content of the response
print(chat_response.choices[0].message.content)